import "./globals.css";

export const metadata = {
  title: "Jeremiah | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/assets/logo.svg" />
      </head>
      <body className="bg-primary scroll-smooth">{children}</body>
    </html>
  );
}
