import type { Metadata } from "next";
import { IBM_Plex_Sans, Space_Mono } from "next/font/google";
import "./globals.css";
import { PageTitleProvider, StateProvider } from "@/context";
import { ThemeProvider } from "next-themes";
import { ViewportHeightSetter } from "@/context/ViewportProvider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { HeaderWithTitle } from "@/components/header-with-title";
import { Toaster } from "@/components/toaster";
// import { Toaster } from "sonner"

const ibmSans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-space-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibmSans.variable} ${spaceMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ViewportHeightSetter />
          <StateProvider>
            <PageTitleProvider>
              <SidebarProvider className="font-sans">
                <AppSidebar />
                  <SidebarInset>
                    <HeaderWithTitle />
                    {children}
                  </SidebarInset>
              </SidebarProvider>
            </PageTitleProvider>
            <Toaster />
          </StateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
